This notebook contains code to vectorize the artist and song names. Unfortunately, we completed this too late to make it part of the app's model. But I'm including it anyway for posterity.

In [6]:
import pandas as pd

df = pd.read_pickle('df_v2.pkl')
print(df.shape)
df.head()

(215383, 17)

   id                  songid  ... duration_ms time_signature
0   0  5PS5dpaLogPzYU9hWiWyZb  ...    157307.0            4.0
1   1  41RpZW2lxAdnqDd2nMBzLQ  ...    138960.0            4.0
2   2  2poHURuOfVNbzZdivAwtOH  ...    514290.0            4.0
3   3  1jg9hZnReygpBvV2axGuPy  ...    212413.0            4.0
4   4  3GsS8jzoixpCnp4jDWCEvb  ...    221200.0            4.0

[5 rows x 17 columns]

In [7]:
df = df.fillna('')

strings = []
for i in range(len(df)):
  string = df.loc[i, 'artist'] + ' ' + df.loc[i, 'track']
  strings.append(string)

strings[:5]

['Karkkiautomaatti Tanssi vaan',
 'Hudson Mohawke No One Could Ever',
 'Der Mystic Tangle Of Aspens',
 'Sasha / Turbulence We Have Got Love',
 "Kris Kross 2 Da Beat Ch'yall"]

In [10]:
df2 = df.copy()

df2['strings'] = strings
df2.head()

   id  ...                              strings
0   0  ...         Karkkiautomaatti Tanssi vaan
1   1  ...     Hudson Mohawke No One Could Ever
2   2  ...          Der Mystic Tangle Of Aspens
3   3  ...  Sasha / Turbulence We Have Got Love
4   4  ...         Kris Kross 2 Da Beat Ch'yall

[5 rows x 18 columns]

In [0]:
import spacy
from spacy.tokenizer import Tokenizer

nlp = spacy.load('en_core_web_lg')

tokenizer = Tokenizer(nlp.vocab)

In [0]:
def get_lemmas(text):
  lemmas = []
  doc = nlp(text)

  for token in doc:
    if ((token.is_stop is False) and (token.is_punct is False) and
        (token.pos_ is not 'PRON')):
      lemmas.append(token.lemma_)

  return lemmas

In [12]:
df2['lemmas'] = df2['strings'].apply(get_lemmas)
df2.head()

   id  ...                               lemmas
0   0  ...     [Karkkiautomaatti, Tanssi, vaan]
1   1  ...                    [Hudson, Mohawke]
2   2  ...         [Der, Mystic, Tangle, aspen]
3   3  ...       [Sasha, turbulence, Got, Love]
4   4  ...  [Kris, Kross, 2, Da, beat, Ch'yall]

[5 rows x 19 columns]

In [14]:
def get_word_vectors(l):
  return [nlp(doc).vector for doc in l]

df2['vectors'] = df2['lemmas'].apply(get_word_vectors)

df2.head()

   id  ...                                            vectors
0   0  ...  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...
1   1  ...  [[0.072683, -0.11776, 0.031957, -0.11951, 0.12...
2   2  ...  [[-0.18212, 0.25999, 0.14923, -0.1657, -0.1460...
3   3  ...  [[-0.035967, 0.18672, 0.20823, 0.21996, -0.079...
4   4  ...  [[-0.083033, 0.05436, 0.68964, 0.12892, -0.328...

[5 rows x 20 columns]

In [0]:
df2.to_pickle('df_vector.pkl')